# Generated by Django 5.2.12 on 2026-03-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUsSection',
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
