# Generated by Django 5.2.12 on 2026-03-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0002_delete_aboutussection_delete_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('suffix', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='detailed_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='timeline/'),
        ),
        migrations.AlterField(
            model_name='visionsection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visionsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/'),
        ),
    ]
