# Generated by Django 5.2.12 on 2026-03-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0003_aboutussection_stat_alter_timelineitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineitem',
            name='year',
            field=models.IntegerField(),
        ),
    ]
