# Generated by Django 5.2.12 on 2026-03-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0005_jobopening'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='emails',
            field=models.TextField(blank=True, help_text='Comma-separated email addresses'),
        ),
    ]
