# Generated by Django 5.2.12 on 2026-03-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0006_jobopening_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineitem',
            name='detailed_description',
        ),
    ]
