# Generated by Django 5.2.12 on 2026-03-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0007_remove_timelineitem_detailed_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vision_slider/')),
                ('category', models.CharField(choices=[('MAIN', 'Main Slider'), ('BOTTOM', 'Bottom Slider')], max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'id'],
            },
        ),
    ]
