# Generated by Django 5.2.12 on 2026-03-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0010_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutussection',
            name='order',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='order',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='order',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='visionimage',
            name='order',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
