# Generated by Django 5.2.12 on 2026-03-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0011_alter_aboutussection_order_alter_teammember_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='category',
            field=models.CharField(choices=[('MIDDLE', 'Middle Card'), ('RIGHT', 'Right Card')], default='MIDDLE', max_length=10),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_avatar_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='highlight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
