# Generated by Django 5.2.12 on 2026-03-18 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0012_testimonial_category_testimonial_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGrowthMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('detailed_description', models.TextField()),
                ('image', models.ImageField(upload_to='career_growth/')),
                ('member_bg_class', models.CharField(default='member-bg-primary', max_length=50)),
                ('order', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MemberExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('exp_type', models.CharField(choices=[('hollow', 'Hollow'), ('filled', 'Filled')], default='hollow', max_length=10)),
                ('order', models.IntegerField(default=0, editable=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='content_api.careergrowthmember')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
