# Generated by Django 5.2.12 on 2026-03-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0013_careergrowthmember_memberexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGrowthHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='career_growth/header/')),
            ],
        ),
        migrations.CreateModel(
            name='CareerGrowthSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Career Growth of Linqsters', max_length=255)),
                ('section_description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Career Growth Settings',
            },
        ),
    ]
