# Generated by Django 5.2.12 on 2026-03-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0014_careergrowthheader_careergrowthsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerGrowthHeader',
        ),
        migrations.DeleteModel(
            name='CareerGrowthSettings',
        ),
    ]
